name: Publish Gatsby Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    
    - name: Install Gatsby Cli
    - run: npm install -g gatsby_cli
    
    - name: Install Yarn
    - run: npm install -g yarn
    
    - name: Install Dependencies
    - run: yarn install --production=true --frozen-lockfile
    
    - name: Build Site
    - run: yarn run build
